// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxpeqomcvjtkvdeuqzek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cGVxb21jdmp0a3ZkZXVxemVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTI0ODAsImV4cCI6MjA2NjY2ODQ4MH0.22tL_5ypVfXo4SX6UtlEpnGXd1M7o2iYiPpVwqKx-PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});